//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    
    public partial class ProductoGetAll_Result2
    {
        public int IdProducto { get; set; }
        public string ProductoNombre { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string ProveedorNombre { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public string DepartamentoNombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdArea { get; set; }
        public int AreaNombre { get; set; }
    }
}
