//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    
    public partial class VentaProductoGetByIdVenta_Result1
    {
        public int IdVentaProducto { get; set; }
        public int IdVenta { get; set; }
        public int Cantidad { get; set; }
        public int IdProducto { get; set; }
        public string ProductoNombre { get; set; }
        public Nullable<decimal> ProductoPrecioUnitario { get; set; }
        public string ProductoDescripcion { get; set; }
        public byte[] ProductoImagen { get; set; }
        public decimal VentaTotal { get; set; }
    }
}
