//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.VentaProductoes = new HashSet<VentaProducto>();
        }
    
        public int IdVenta { get; set; }
        public string UserName { get; set; }
        public decimal Total { get; set; }
        public int IdMetodoPago { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual ICollection<VentaProducto> VentaProductoes { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
